[package]
name = "ping-game"
version = "0.1.0"

[[bin]]
name = "ping-game"

[dependencies]
piston = "0.37.0"
piston2d-graphics = "0.26.0"
pistoncore-sdl2_window = "0.50.0"
piston2d-opengl_graphics = "0.53.0"
